version: '4.9'

networks:
  nginx-php8-mysql8:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8-service
      - mysql8-service
    networks:
      - nginx-php8-mysql8

  # php
  php8-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php8-mysql8

  # mysql
  mysql_db:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always #always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - nginx-php8-mysql8

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - php8-service
      - mysql8-service
    networks:
      - nginx-php8-mysql8



